### ISSUE TITLE
RLS: 1.8.0

### ISSUE THREAD

**Issue by kittoku** [kittoku/Open-SSTP-Client#137]
This is a private issue.

- [x] Implement EAP-MSCHAPV2 (#131)
- [x] Keep notification displayed (#133)
- [x] Log which certificate produces an error (#125)
