### ISSUE TITLE
RLS: 1.2.0

### ISSUE THREAD

**Issue by kittoku** [kittoku/Open-SSTP-Client#23]
This is a private issue. 

- [x] route only LAN (#18, #21)
- [x] show assigned addresses (#18)
- [x] reconnection setting (#19)
- [x] change the word (#24)
- [x] terms of contribution (#27)

**Comment by tormentous** [comment]
whats the status?

**Comment by kittoku** [comment]
I still have intention to develop. Sorry for my laziness.
